### ISSUE TITLE
Some errors with Kirby 2.2

### ISSUE THREAD

**Issue by 1n3JgKl9pQ6cUMrW** [FabianSperrle/kirby-stats#15]
The plugin is not working quite good using Kirby 2.2

The "most visited" pages do not show up, so I had to alter the .css-code with these lines;

``` CSS
/* fine-tune / fix the stats-widget */

#stats-widget .dashboard-box {
  position: initial;
}

#stats2 .icon {
  display: none;
}

#stats2 li {
  position: initial;
}

#stats-widget a {
  display: inline-block;
  padding: .25em .5em;
}
```

But it is also only logging visits to the homepage - all the other pages are ignored, it seemed?
